# Simple workflow pour déployer du contenu statique vers GitHub Pages
name: Deploy static content to Pages

on:
  # S'execute lors de push dans la branche par defaut
  push:
    branches: ['master']

  # Autorise à executer ce workflow manuellement depuis l'onglet Actions
  workflow_dispatch:

# Définie les permissions du GITHUB_TOKEN pour autoriser le déployement vers GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Autoriser un déployement concurrent
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Création d'une tâche unique car nous sommes juste en train de déployer
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload le dossier dist
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
